### ISSUE TITLE
CMake + vcpkg

### ISSUE THREAD

**Issue by luciy-marciy** [smurfomen/QSerializer#2]
Как насчёт добавления поддержки CMake?  Так как Qt6 будет переходить именно на этот генератор сборочных систем. Плюс CMake сейчас практически стандарт.

А до кучи можно ещё и вкинуть либу в vcpkg, ибо любые библиотеки нужны C++ сообществу.

**Comment by smurfomen** [comment]
Да, я подозреваю, что qmake совсем уйдет из нашего обихода. Согласен, причины для добавления CMake железные.Как появится кусочек свободного времени - займусь этим, сейчас я делаю бенчмарки.
Если честно, не задумывался над тем, что бы закинуть ее в какой-то пакетный менеджер, спасибо за наводку!

**Comment by smurfomen** [comment]
Ув. @luciy-marciy , Я переработал QSerializer, и он перестал быть библиотекой как таковой. Сейчас я вижу это как небольшой wrapper для вашего Qt/C++ кода. Фактически, я смог урезать объем QSerializer до одного файла. Насколько это удачное решение - не мне судить. На текущий момент, QSerializer представляет, в большинстве своем, набор макросов для генерации Q_PROPERTY и функций доступа и преобразования JSON и XML в сгенерированное поле класса. Чтобы пользоваться всем функционалом QSerializer достаточно унаследоваться от одноименного класса и задекларировать поля для сериализации.

**Comment by ohmree** [comment]
Hi, I think this is still an issue and that it would be nice to have a `CMakeLists.txt` file, so even if this isn't on vcpkg or some other platform we could use git submodules and just call `add_subdirectory` from cmake to automatically get the right flags for using this.

Would you be willing to merge a PR for this?

(Note that I'm not the best at cmake and am only using it because it's the canonical build tool for qt, so my future contribution could probably be improved upon).
